export const leverSelectors = {
  form: '#application-form',
  question: '#application-form .application-question',
  jobHeading: '.posting-headline h2, h2',
  jobDescription: '.content',
  submit: '#application-form #btn-submit, #application-form button[type="submit"], #application-form input[type="submit"], #application-form .template-btn-submit, #application-form [data-qa="btn-submit"]',
  resume: '#resume-upload-input, input[data-qa="input-resume"]',
  resumeButton: '.visible-resume-upload',
  resumeParsing: '.resume-upload-working',
  resumeSuccess: '.resume-upload-success',
  resumeFailure: '.resume-upload-failure, .resume-upload-oversize',
  resumeFilename: '.visible-resume-upload .filename',
  resumeStorageId: 'input[name="resumeStorageId"]',
  locationResults: '.dropdown-results',
  captchaChallenge: [
    'iframe[src*="hcaptcha.com"]',
    'iframe[src*="captcha"]',
    'iframe[title*="hCaptcha" i]',
    'iframe[title*="challenge" i]',
    '.h-captcha',
    '[data-hcaptcha-widget-id]',
    'iframe[src*="recaptcha/api2/bframe"]',
    'iframe[src*="recaptcha/enterprise/bframe"]',
  ].join(', '),
} as const
